# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2

updates:
  # Enable version updates for uv
  - package-ecosystem: "uv"
    commit-message:
      include: "scope"
      prefix: "chore"
    directory: "/"
    labels:
      - dependencies
    reviewers:
      - xmartlabs/python
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    commit-message:
      include: "scope"
      prefix: "chore"
    directory: "/"
    labels:
      - dependencies
    reviewers:
      - xmartlabs/python
    schedule:
      interval: "weekly"
