# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit, pre-push]
files: ^src/|^alembic/versions/
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --select=I, --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        exclude: ^src/alembic/|^scripts/|^\\.devcontainer/|^\\.github/
        additional_dependencies: [
          fastapi==0.115.12,
          pydantic==2.10.6,
          pydantic-settings==2.8.1,
          sqlalchemy==2.0.39,
          asyncpg==0.30.0,
          structlog==25.3.0,
          sqladmin==0.20.1,
          fastapi-pagination==0.12.34,
          opentelemetry-api==1.31.1,
          opentelemetry-sdk==1.31.1,
          opentelemetry-instrumentation-fastapi==0.52b1,
          opentelemetry-instrumentation-sqlalchemy==0.52b1,
          opentelemetry-exporter-otlp==1.31.1,
          celery==5.4.0,
          python-jose==3.4.0,
          passlib==1.7.4,
          uvicorn==0.34.0,
          httpx==0.28.1,
          pytest==8.3.5,
          ptpython==3.0.29
        ]
