"""test migrations

Revision ID: babbbc01361e
Revises: e9bd7c60fa81
Create Date: 2025-03-24 17:57:57.813068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babbbc01361e'
down_revision = 'e9bd7c60fa81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('total_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'total_quantity')
    # ### end Alembic commands ###
