name: CI Pipeline Template

'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-format:
    name: Run Linters & Formatters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root --with dev

      - name: Run linters and formatters
        run: |
          poetry run python -m pycln src --exclude __init__.py --all
          poetry run python -m isort src
          poetry run python -m mypy src
          poetry run python -m black src --quiet --exclude alembic
          poetry run python -m flake8 src

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dev -d dev"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PROJECT_NAME: python-template
      DATABASE_URL: postgresql://dev:dev@localhost:5432/dev
      ASYNC_DATABASE_URL: postgresql+asyncpg://dev:dev@localhost:5432/dev
      DATABASE_POOL_PRE_PING: True
      DATABASE_POOL_SIZE: 5
      DATABASE_POOL_RECYCLE: 3600
      DATABASE_MAX_OVERFLOW: 10
      LOG_LEVEL: DEBUG
      SERVER_URL: example.com
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root --with dev

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage report -m --fail-under=80

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t python-template:latest .
